CREATE DATABASE PSBoot;
use PSBoot;

SET default_storage_engine = INNODB;

CREATE TABLE STATUS
(
    ID int(11) NOT NULL AUTO_INCREMENT,
    STATUS_NAME varchar (50) NOT NULL,
    HTMLCOLOR varchar (10) Not NULL,
    HTML_Description varchar (50),
    PRIMARY KEY (ID),
    UNIQUE (STATUS_NAME),
    date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE SYSTEMS
-- Allows for Systems to run different versions of the PowerShell applications.
(
    ID int(11) NOT NULL AUTO_INCREMENT,
    SYSTEM_NAME varchar (50) NOT NULL,
	STATUS_ID int(11) NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE (SYSTEM_NAME),
	FOREIGN KEY (STATUS_ID) REFERENCES STATUS (ID),
    date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE APPLICATIONS
-- Defines the basic Application
(
    ID int(11) NOT NULL AUTO_INCREMENT,
    APPLICATION_NAME varchar (50) NOT NULL,
    STATUS_ID int(11) NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE (APPLICATION_NAME),
    FOREIGN KEY (STATUS_ID) REFERENCES STATUS (ID),
    date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE APPLICATION_VERSIONS
-- Defines available versions of the Applications
(
    ID int(11) NOT NULL AUTO_INCREMENT,
    APPLICATION_VERSION varchar (50) NOT NULL,
    APPLICATION_ID int(11) NOT NULL,
    STATUS_ID int(11) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (APPLICATION_ID) REFERENCES APPLICATIONS (ID),
    FOREIGN KEY (STATUS_ID) REFERENCES STATUS (ID),
    date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE MODULES
-- Defines the basic Module names
(
    ID int(11) NOT NULL AUTO_INCREMENT,
    MODULE_NAME varchar (50) NOT NULL,
    STATUS_ID int(11) NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE (MODULE_NAME),
    FOREIGN KEY (STATUS_ID) REFERENCES STATUS (ID),
    date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE MODULE_VERSIONS
-- Defines the available module versions
(
    ID int(11) NOT NULL AUTO_INCREMENT,
    MODULE_VERSION varchar (50) NOT NULL,
    MODULE_ID int(11) NOT NULL,
    STATUS_ID int(11) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (MODULE_ID) REFERENCES MODULES (ID),
    FOREIGN KEY (STATUS_ID) REFERENCES STATUS (ID),
    date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE SYSTEM_APPLICATIONS
-- Defines the specific applications/version combination to install for the System
(
    ID int(11) NOT NULL AUTO_INCREMENT,
    SYSTEM_ID int(11) NOT NULL,
    APP_VER_ID int(11) NOT NULL, 
    STATUS_ID int(11) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (SYSTEM_ID) REFERENCES SYSTEMS (ID),
    FOREIGN KEY (STATUS_ID) REFERENCES STATUS (ID),
    FOREIGN KEY (APP_VER_ID) REFERENCES APPLICATION_VERSIONS (ID),
    date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE APPLICATION_MODULES
-- Defines the specific Module versions for a specific Application version
(
    ID int(11) NOT NULL AUTO_INCREMENT,
    MOD_VER_ID int(11) NOT NULL,
    APP_VER_ID int(11) NOT NULL, 
    STATUS_ID int(11) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (MOD_VER_ID) REFERENCES MODULE_VERSIONS (ID),
    FOREIGN KEY (STATUS_ID) REFERENCES STATUS (ID),
    FOREIGN KEY (APP_VER_ID) REFERENCES APPLICATION_VERSIONS (ID),
    date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);